name: postgrest
description: PostgREST client for Dart. This library provides an ORM interface to PostgREST.
version: 0.1.10+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0

dev_dependencies:
  lint: ^1.3.0
  test: ^1.15.4
