name: postgrest
description: A PostgREST api client written in Dartlang.
version: 0.0.1-dev.3
homepage: "https://supabase.io"
repository: "https://github.com/supabase/postgrest-dart"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.3.0